# Default values for django-admin.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2
namespace: practice
image:
  repository: gcr.io/practice-230207/django-app
  tag: v1
  pullPolicy: Always

service:
  name: django-admin-service
  labels: django-admin
  type: NodePort
  port: 80
  targetPort: 8000
  selector: django-admin


deployment:
  name: django-admin
  labels: django-admin
  strategy:
    maxSurge: 1
    maxUnavailable: 1
  container:
    name: django-admin
    containerPort: 8000
    resources:
      requests:
        memory: 256Mi
        cpu: 200m
      limits:
        memory: 512Mi
        cpu: 500m
  proxySql:
    image: b.gcr.io/cloudsql-docker/gce-proxy:1.09
    name: cloudsql-proxy
    instances: practice-230207:us-central1:django-instance=tcp:5432
    credential_path: /secrets/cloudsql
    resources:
      requests:
        memory: 256Mi
        cpu: 100m
      limits:
        memory: 512Mi
        cpu: 200m

  readinessProbe:
    path: /app-v1/healthy/
    port: 8000
    initialDelaySeconds: 30
    timeoutSeconds: 10
    periodSeconds: 15
  livenessProbe:
    path: /app-v1/healthy/
    port: 8000
    periodSeconds: 15
    initialDelaySeconds: 30
    timeoutSeconds: 10

  env:
    dbUser:
      name: cloudsql-oauth-credentials
      key: database-user
    dbPass:
      name: cloudsql-oauth-credentials
      key: database-pass
  volumes:
    name: cloudsql-oauth-credentials
    secretName: cloudsql-oauth-credentials

