apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name | quote }}
  namespace: {{ .Values.namespace }}
  labels:
    name: {{ .Values.service.labels }}
spec:
  type: {{ .Values.service.type }}
  ports:
    # the port that this service should serve on
  - protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
  selector:
    app: {{ .Values.service.selector }}
