apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  namespace: {{ .Values.namespace }}
  annotations:
    "helm.sh/hook": pre-install
type: Opaque
data:
  database-pass: {{ .Values.secret.data.pass }}
  database-user: {{ .Values.secret.data.user }}
  credentials.json: {{ .Values.secret.data.credentials }}
